# Generated by Django 6.0.2 on 2026-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
